### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by mvaudel** [lejon/T-SNE-Java#5]
Hi,

When trying to run the example of the main page, t-SNE returns an error:
```
java.lang.NumberFormatException: For input string: "1.0000000e+00   1.0000000e+00   1.0000000e+00   1.0000000e+00...
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.jujutsu.utils.MatrixUtils.simpleRead2DMatrix(MatrixUtils.java:26)
```

Looks like your column delimiter is wrong. You might want to change
```
double [][] X = MatrixUtils.simpleRead2DMatrix(new File("src/main/resources/datasets/mnist2500_X.txt"), ",");
```
into
```
double [][] X = MatrixUtils.simpleRead2DMatrix(new File("src/main/resources/datasets/mnist2500_X.txt"), "   ");
```

Thank you,

Marc

**Comment by lejon** [comment]
Thanks, for the heads up, I'll have a look at it!

Cheers!
-Leif
